<?php
/**
 * WEB4PRO - Creating profitable online stores
 *
 *
 * @author    WEB4PRO <support@web4pro.net>
 * @category  WEB4PRO
 * @package   Web4pro_Fastorder
 * @copyright Copyright (c) 2014 WEB4PRO (http://www.web4pro.net)
 * @license   http://www.web4pro.net/license.txt
 */
/* @var $this Web4pro_Fastorder_Block_Captcha_Recaptcha */
?>
<?php $captcha = $this->getCaptchaModel() ?>
<?php $theme = $captcha->getTheme(); ?>

<?php if ($theme == 'local'): ?>
    <script>
        var RecaptchaOptions = {
            theme: 'custom',
            lang: '<?php echo $captcha->getLanguage(); ?>',
            custom_theme_widget: 'recaptcha_widget'
        };
    </script>
    <div id="recaptcha_widget" class="group-select wide fieldset" style="display:none">
        <div class="col2-set">
            <div class="col-1" style="width: 310px; margin-right: 10px; background: transparent; border: 0px none;">
                <div id="recaptcha_image" style="border: 1px solid #CCCCCC; margin-bottom: 10px;"></div>
                <div style="text-align: left;">
                    <span class="recaptcha_only_if_image"><?php echo $this->__(
                            'Type the image letters or numbers'
                        ); ?></span>
                    <span class="recaptcha_only_if_audio"><?php echo $this->__('Type what you hear'); ?></span>
                    <input type="text" id="recaptcha_response_field" name="recaptcha_response_field"
                           class="input-text required-entry"/>
                </div>
            </div>
            <div class="col-2" style="float: left; width: 25px; background: transparent; border: 0px none;">
                <div><a href="javascript:Recaptcha.reload()"><img
                            src="<?php echo $this->getSkinUrl('recaptcha/images/refresh.png'); ?>"
                            title="<?php echo $this->__('Load Another Image'); ?>"
                            alt="<?php echo $this->__('Load Another Image'); ?>"/></a></div>
                <div class="recaptcha_only_if_image"><a href="javascript:Recaptcha.switch_type('audio')"><img
                            src="<?php echo $this->getSkinUrl('recaptcha/images/sound.png'); ?>"
                            title="<?php echo $this->__('Get an audio challenge'); ?>"
                            alt="<?php echo $this->__('Get an audio challenge'); ?>"/></a></div>
                <div class="recaptcha_only_if_audio"><a href="javascript:Recaptcha.switch_type('image')"><img
                            src="<?php echo $this->getSkinUrl('recaptcha/images/text.png'); ?>"
                            title="<?php echo $this->__('Get a visual challenge'); ?>"
                            alt="<?php echo $this->__('Get a visual challenge'); ?>"/></a></div>
                <div><a href="javascript:Recaptcha.showhelp()"><img
                            src="<?php echo $this->getSkinUrl('fontis/recaptcha/images/help.png'); ?>"
                            title="<?php echo $this->__('help'); ?>" alt="<?php echo $this->__('help'); ?>"/></a></div>
            </div>
        </div>

    </div>
<?php elseif ($theme == 'New'): ?>
    <script type="text/javascript">
        var onloadCallback = function () {
            grecaptcha.render('recaptcha_html_element', {
                'sitekey': '<?php echo $captcha->getPublicKey(); ?>'
            });
        };
    </script>
    <div class="g-recaptcha" data-sitekey="6Lfy0iMUAAAAACtXMcbAUnyp2u8HMyqarc7Kr9mH"></div>
<!--    <div id="recaptcha_html_element"></div>-->
    <script src="https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit" async defer></script>
<?php else: ?>
    <script type="text/javascript">
        var RecaptchaOptions = {
            lang: '<?php echo $captcha->getLanguage(); ?>',
            theme: '<?php echo $theme ?>',
        };
    </script>
    <script type="text/javascript" src="<?php echo $captcha->getUrl(); ?>"></script>
<?php endif; ?>